### ISSUE TITLE
Send to CRAN the new version of Rwtss

### ISSUE THREAD

**Issue by OldLipe** [e-sensing/Rwtss#12]

**Comment by OldLipe** [comment]
I think Rwtss is ready to submit to CRAN. @gilbertocamara, can I submit it?

**Comment by gilbertocamara** [comment]
Hi Felipe 

Yes, please submit Rwtss to CRAN.

Thanks
Gilberto

**Comment by OldLipe** [comment]
OK. So I'll add me as a package maintainer. 

Thanks!

**Comment by OldLipe** [comment]
Rwtss on its way to CRAN.

Link: https://CRAN.R-project.org/package=Rwtss
